# Generated by Django 3.1 on 2020-08-19 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('okpd', models.CharField(max_length=12, unique=True)),
                ('ktru_records_count', models.CharField(max_length=30)),
                ('isCanceled', models.BooleanField()),
                ('zapret', models.CharField(max_length=20)),
                ('ogranichenia', models.CharField(max_length=20)),
                ('preimuschestvo', models.CharField(max_length=20)),
                ('dopusk', models.CharField(max_length=20)),
                ('perechen', models.CharField(max_length=20)),
                ('forma', models.CharField(max_length=20)),
                ('tk', models.CharField(max_length=20)),
                ('efektivnost', models.CharField(max_length=20)),
                ('perechenTryUIS', models.CharField(max_length=20)),
                ('nepubl', models.CharField(max_length=20)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('got_results', models.BooleanField()),
            ],
        ),
    ]
