# Generated by Django 3.1 on 2020-08-19 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200819_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='dopusk',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='efektivnost',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='forma',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='got_results',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='isCanceled',
            field=models.BooleanField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='ktru_records_count',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='nepubl',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='ogranichenia',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='perechen',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='perechenTryUIS',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='preimuschestvo',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='tk',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='zapret',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
